config/routes.rb
Rails.application.routes.draw do

  resources :orders
  resources :customers
  resources :dresses
  get 'shop/index'

	resources :admins
	
	resources :dresses do
		resources :comments
	end

  
  controller :sessions do
	get 'login'=> :new
	post 'login' => :create
	get 'logout'=> :destroy
	delete 'logout'=> :destory
	get 'adminlogin' => :adminnew
	post 'adminlogin' => :admincreate
	get'adminlogout' => :admindestroy
	delete 'adminlogout' => :admindestroy
  end
  
  get 'search' =>'dresses#search'
  
  resources :lineitems
  resources :carts do
  	resources :lineitems
  end

	

  resources :dress_styles

   root 'pages#home'

end

app/models/admin.rb
class Admin < ActiveRecord::Base

	has_secure_password
end

app/models/cart.rb
class Cart < ActiveRecord::Base

	has_many :lineitems
	
	def add_dress(dress_id)
		current_item = lineitems.find_by_dress_id(dress_id)
		if current_item
			current_item.quantity +=1
		else
			current_item = lineitems.new(dress_id: dress_id)
			current_item.quantity = 1
		end
			current_item
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	
	belongs_to :customer
	belongs_to :dress

end

app/models/customer.rb
class Customer < ActiveRecord::Base
   
	has_secure_password
	geocoded_by :address
	after_validation :geocode, :if => :address_changed?
	has_many :comments
	has_many :orders
	validates :email, presence: true
	validates :name, presence: true
	validates :password, presence: true
	#validates :email, uniqueness: true
  
end

app/models/dress.rb
class Dress < ActiveRecord::Base

	has_many :lineitems

   belongs_to :dress_style
   
   has_many :comments, :dependent => :destroy
   
   validates :size, presence: true
   validates :colour, presence: true
   
   def average_stars
   		comments.average(:stars)
   	end
   	
   	def self.search(query)
   		where("colour LIKE?", "%#{query}%")
   	end
end

app/models/dress_style.rb
class DressStyle < ActiveRecord::Base

    has_many :dresses, dependent: :destroy
	
	validates :style, presence: true
	
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base

	belongs_to :cart
	belongs_to :dress
	belongs_to :orders
	
end

app/models/order.rb
class Order < ActiveRecord::Base

	belongs_to :customer
	has_many :lineitems
	
	def add_lineitems_from_cart(cart)
		cart.lineitems.each do |item|
		item.cart_id = nil
		lineitems << item
		end
	end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def index
  	@dresses = Dress.all
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

def signed_in?
	if session[:customer_id].nil?
		return
	else
		@current_customer = Customer.find_by_id(session[:customer_id])
	end
end

def adminsigned_in?
	if session[:admin_id].nil?
		return
	else
		@admincurrent_admin = Admin.find_by_id(session[:admin_id])
	end
end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dresses_helper.rb
module DressesHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admins</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.email %></td>
        <td><%= admin.password_digest %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @admin.password_digest %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DressRental1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="banner">
     <%=image_tag("dress_rental.jpg", :size=>"100x50")%>
     <%="Dress Rental" %>
</div>

<div id="columns">
  <ul>
  	<li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Dresses", dresses_path %></li>
	<li><%= link_to "Dress Styles", dress_styles_path %></li>
	<li><%= link_to "Rent Dress", shop_index_path %></li>
	
	<% if !signed_in? %>
		<li><%= link_to "Sign In", login_path%></li>
	<% else %>
		<li>Signed in as <%= @current_customer.name %></li>
		<li><%= link_to "Sign Out", logout_path %></li>
	<%end%>
	
	<% if !adminsigned_in? %>
		<li><%= link_to "Admin Sign In", adminlogin_path%></li>
	<% else %>
		<li>Admin: <%= @admincurrent_admin.email %></li>
		<li><%=link_to "Sign Out", adminlogout_path %></li>
	<% end %>
	<li><%= render '/dresses/search'%></li>
  </ul>
</div>
	
	 
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<!DOCTYPE>
<html>
<h1>Our location</h1>
<body>
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{53.2878}%2C#{6.2036}" %>
</body>
</html>