config/routes.rb
Rails.application.routes.draw do

  resources :orders
  resources :customers
  resources :dresses
  get 'shop/index'

	resources :admins
	
	resources :dresses do
		resources :comments
	end

  
  controller :sessions do
	get 'login'=> :new
	post 'login' => :create
	get 'logout'=> :destroy
	delete 'logout'=> :destory
	get 'adminlogin' => :adminnew
	post 'adminlogin' => :admincreate
	get'adminlogout' => :admindestroy
	delete 'adminlogout' => :admindestroy
  end
  
  get 'search' =>'dresses#search'
  
  resources :lineitems
  resources :carts do
  	resources :lineitems
  end

	

  resources :dress_styles

   root 'pages#home'

end

app/models/admin.rb
class Admin < ActiveRecord::Base

	has_secure_password
end

app/models/cart.rb
class Cart < ActiveRecord::Base

	has_many :lineitems
	
	def add_dress(dress_id)
		current_item = lineitems.find_by_dress_id(dress_id)
		if current_item
			current_item.quantity +=1
		else
			current_item = lineitems.new(dress_id: dress_id)
			current_item.quantity = 1
		end
			current_item
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	
	belongs_to :customer
	belongs_to :dress

end

app/models/customer.rb
class Customer < ActiveRecord::Base
   
	has_secure_password
	geocoded_by :address
	after_validation :geocode, :if => :address_changed?
	has_many :comments
	has_many :orders
	validates :email, presence: true
	validates :name, presence: true
	validates :password, presence: true
	#validates :email, uniqueness: true
  
end

app/models/dress.rb
class Dress < ActiveRecord::Base

	has_many :lineitems

   belongs_to :dress_style
   
   has_many :comments, :dependent => :destroy
   
   validates :size, presence: true
   validates :colour, presence: true
   
   def average_stars
   		comments.average(:stars)
   	end
   	
   	def self.search(query)
   		where("colour LIKE?", "%#{query}%")
   	end
end

app/models/dress_style.rb
class DressStyle < ActiveRecord::Base

    has_many :dresses, dependent: :destroy
	
	validates :style, presence: true
	
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base

	belongs_to :cart
	belongs_to :dress
	belongs_to :orders
	
end

app/models/order.rb
class Order < ActiveRecord::Base

	belongs_to :customer
	has_many :lineitems
	
	def add_lineitems_from_cart(cart)
		cart.lineitems.each do |item|
		item.cart_id = nil
		lineitems << item
		end
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, :dress_id, :lineitem_id)
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  before_action :adminauthorise, only: [:edit, :update, :destroy, :show]


  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
      	Usermailer.welcome(@customer).deliver
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :email, :phoneNumber, :password)
    end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def index
  	@dresses = Dress.all
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

def signed_in?
	if session[:customer_id].nil?
		return
	else
		@current_customer = Customer.find_by_id(session[:customer_id])
	end
end

def adminsigned_in?
	if session[:admin_id].nil?
		return
	else
		@admincurrent_admin = Admin.find_by_id(session[:admin_id])
	end
end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dress_styles_helper.rb
module DressStylesHelper
end

app/helpers/dresses_helper.rb
module DressesHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phoneNumber %><br>
    <%= f.number_field :phoneNumber %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phonenumber</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.phoneNumber %></td>
        <td><%= customer.password_digest %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @customer.phoneNumber %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @customer.password_digest %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>