config/routes.rb
Rails.application.routes.draw do

  resources :orders
  resources :customers
  resources :dresses
  get 'shop/index'

	resources :admins
	
	resources :dresses do
		resources :comments
	end

  
  controller :sessions do
	get 'login'=> :new
	post 'login' => :create
	get 'logout'=> :destroy
	delete 'logout'=> :destory
	get 'adminlogin' => :adminnew
	post 'adminlogin' => :admincreate
	get'adminlogout' => :admindestroy
	delete 'adminlogout' => :admindestroy
  end
  
  get 'search' =>'dresses#search'
  
  resources :lineitems
  resources :carts do
  	resources :lineitems
  end

	

  resources :dress_styles

   root 'pages#home'

end

app/models/admin.rb
class Admin < ActiveRecord::Base

	has_secure_password
end

app/models/cart.rb
class Cart < ActiveRecord::Base

	has_many :lineitems
	
	def add_dress(dress_id)
		current_item = lineitems.find_by_dress_id(dress_id)
		if current_item
			current_item.quantity +=1
		else
			current_item = lineitems.new(dress_id: dress_id)
			current_item.quantity = 1
		end
			current_item
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	
	belongs_to :customer
	belongs_to :dress

end

app/models/customer.rb
class Customer < ActiveRecord::Base
   
	has_secure_password
	geocoded_by :address
	after_validation :geocode, :if => :address_changed?
	has_many :comments
	has_many :orders
	validates :email, presence: true
	validates :name, presence: true
	validates :password, presence: true
	#validates :email, uniqueness: true
  
end

app/models/dress.rb
class Dress < ActiveRecord::Base

	has_many :lineitems

   belongs_to :dress_style
   
   has_many :comments, :dependent => :destroy
   
   validates :size, presence: true
   validates :colour, presence: true
   
   def average_stars
   		comments.average(:stars)
   	end
   	
   	def self.search(query)
   		where("colour LIKE?", "%#{query}%")
   	end
end

app/models/dress_style.rb
class DressStyle < ActiveRecord::Base

    has_many :dresses, dependent: :destroy
	
	validates :style, presence: true
	
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base

	belongs_to :cart
	belongs_to :dress
	belongs_to :orders
	
end

app/models/order.rb
class Order < ActiveRecord::Base

	belongs_to :customer
	has_many :lineitems
	
	def add_lineitems_from_cart(cart)
		cart.lineitems.each do |item|
		item.cart_id = nil
		lineitems << item
		end
	end
end

app/controllers/dresses_controller.rb
class DressesController < ApplicationController
  before_action :set_dress, only: [:show, :edit, :update, :destroy]
  before_action :adminauthorise, only: [:create, :new, :edit, :update, :destroy]

  # GET /dresses
  # GET /dresses.json
  def index
    @dresses = Dress.all
  end
  
  def search
  	@dresses = Dress.search params[:query]
  	unless @dresses.empty?
  		render 'index'
  	else
  		flash[:notice] = 'No dresses match that search'
  		@dresses = Dress.all
  		render 'index'
  	end
  end


  # GET /dresses/1
  # GET /dresses/1.json
  def show
  end

  # GET /dresses/new
  def new
    @dress = Dress.new
  end

  # GET /dresses/1/edit
  def edit
  end

  # POST /dresses
  # POST /dresses.json
  def create
  	
    @dress = Dress.new(dress_params)

    respond_to do |format|
      if @dress.save
        format.html { redirect_to @dress, notice: 'Dress was successfully created.' }
        format.json { render :show, status: :created, location: @dress }
      else
        format.html { render :new }
        format.json { render json: @dress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dresses/1
  # PATCH/PUT /dresses/1.json
  def update
    respond_to do |format|
      if @dress.update(dress_params)
        format.html { redirect_to @dress, notice: 'Dress was successfully updated.' }
        format.json { render :show, status: :ok, location: @dress }
      else
        format.html { render :edit }
        format.json { render json: @dress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dresses/1
  # DELETE /dresses/1.json
  def destroy
    @dress.destroy
    respond_to do |format|
      format.html { redirect_to dresses_url, notice: 'Dress was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dress
      @dress = Dress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dress_params
      params.require(:dress).permit(:colour, :size, :price, :image, :dress_style_id, :available)
    end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def index
  	@dresses = Dress.all
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

def signed_in?
	if session[:customer_id].nil?
		return
	else
		@current_customer = Customer.find_by_id(session[:customer_id])
	end
end

def adminsigned_in?
	if session[:admin_id].nil?
		return
	else
		@admincurrent_admin = Admin.find_by_id(session[:admin_id])
	end
end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dress_styles_helper.rb
module DressStylesHelper
end

app/helpers/dresses_helper.rb
module DressesHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/dresses/_form.html.erb
<%= form_for(@dress) do |f| %>
  <% if @dress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dress.errors.count, "error") %> prohibited this dress from being saved:</h2>

      <ul>
      <% @dress.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :dress_style_id %><br>
    <%= f.collection_select :dress_style_id, DressStyle.all, :id, :style %>
  </div>
  <div class="field">
    <%= f.label :available %><br>
    <%= f.check_box :available %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dresses/_search.html.erb
<%=form_tag(search_path, method: :get) do%>
	<%=text_field_tag(:query, params[:query])%>
	<%= submit_tag "Search Dress by Colour" %>
<% end %>

app/views/dresses/edit.html.erb
<h1>Editing Dress</h1>


<%= render 'form' %>

<%= link_to 'Show', @dress %> |
<%= link_to 'Back', dresses_path %>

app/views/dresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dresses</h1>

<table>
  <thead>
    <tr>
      <th>Colour</th>
      <th>Size</th>
      <th>Price</th>
      <th>Image</th>
      <th>Dressstyle</th>
      <th>Available</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dresses.each do |dress| %>
      <tr>
        <td><%= dress.colour %></td>
        <td><%= dress.size %></td>
        <td><%= dress.price %></td>
        <td><%= dress.image %></td>
        <td><%= dress.dress_style.style %></td>
        <td><%= dress.available %></td>
        <td><%= link_to 'Show', dress %></td>
        <td><%= link_to 'Edit', edit_dress_path(dress) %></td>
        <td><%= link_to 'Destroy', dress, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dress', new_dress_path %>

app/views/dresses/new.html.erb
<h1>New Dress</h1>

<%= render 'form' %>

<%= link_to 'Back', dresses_path %>

app/views/dresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Colour:</strong>
  <%= @dress.colour %>
</p>

<p>
  <strong>Size:</strong>
  <%= @dress.size %>
</p>

<p>
  <strong>Price:</strong>
  <%= @dress.price %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @dress.image, :size =>"50x50" %>
</p>

<p>
  <strong>Dressstyle:</strong>
  <%= @dress.dress_style.style %>
</p>

<p>
	<strong>Available:</strong>
	<%= @dress.available %>

<h2>Review and Star Rating :</h2>
	<%= form_for([@dress, Comment.new]) do |f| %>
	
	<h3><%= f.label :stars %>
	<% stars = [1,2,3,4,5] %>
	<% stars.each do |star| %>
		<%= f.radio_button :stars, star %><%=star%>
	<%end%>
	</h3></br>
	<%= f.text_area :content, :rows =>4, :cols => 40 %>
	<div class = "actions">
		<%= f.submit "Post a Comment"%>
	</div>
<%end%>
	
<% if @dress.comments.empty? %>
	<h3>You are the first to comment </h3>
<% else %>
	<h2>Others reviews on this dress:</h2>
	<% @dress.comments.reverse.each do |comment| %>
		<p><%= comment.content %>
		Posted <%= time_ago_in_words(comment.created_at) %> ago by
		<%=comment.customer.name %></p>
	<% end %>
	<h3>Star Rating</h3>
	<p>
		<%= number_with_precision( @dress.average_stars, precision: 0) %>
	</p>
<% end %>


<%= link_to 'Edit', edit_dress_path(@dress) %> |
<%= link_to 'Back', dresses_path %>